language: generic
os:
- linux
- osx
env:
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="http://repo.continuum.io/miniconda/Miniconda-latest"
  - TRAVIS_PYTHON_VERSION="2.7"
  - secure: ncAL8ZXJcEuCH9Z6JyZdP7HtZEr/cJ0jLbEpB7JN4JME0Q0pzL95zT17zPaF0o1cO1uLFnSNBMe89GhiMPAIV7D03QIUGOxTKhNBTBA0/U4HWLlxi0+W9L8a/g0ajS3H+zDpi1ktsU2X+QzysNp0wUq+JOuOlpq8Vj4/eaDGLEaqoTIF+vignw7cujLKGrepdiyCLzZQ+yUx6RgBB0GyOXqx4cFqkbHRYLgN3gqtONfr8PPx39P8sz7d26f64LokCU2lXfEqE3K2aWLtdySZ+UySneb0VVP0iGipn9D1mseFAT/wdrB4kdZNIeael8NyKLj9v9kio/jceje8u+NXiIKGjmvEUUUEeEXUdNkj46bIN2tp0p4FZuXlk7c4N93WBAfVJgVSH/Pv4SIDoKFtg5/Gs5GRRagRv5wDAtYLHp7a/9iZMpmaJKQmuqod3aTglpJGRwhe4aqc3opH3tDO+mZc2uQdDkIzZkRqAXa1Z7zfCJQiz29GcjVuhxJChbobd+PA8m/AiaRXSEewd0G76gJ0QMwndJxEDYZKz10Se0Rwu8wYFfvLXGz3nL/T7i0DpS04qkukyuFb6/d2r5/IuDbd0gtF3zUlxfpc7YOCNk0rsT3wRW7UCUUsO7kPtjfipc8MfI0M3fGrnbE9LmuO7iydd3/gr+QT2I7IZwcmdW0=
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda install python=$TRAVIS_PYTHON_VERSION
- conda install -q conda-build anaconda-client coverage sphinx
script:
- conda build ./recipe -c csdms-stack -c conda-forge
after_success:
- curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py
  > $HOME/anaconda_upload.py
- echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack
  --token=-
